version: '3.1'

services:
  db:
    container_name: db
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: face
      MYSQL_USER: dung
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
      LANG: C.UTF-8
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    platform: linux/amd64
    volumes:
      - ./init:/docker-entrypoint-initdb.d