version: '3.1'

services:
  db:
    container_name: db
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: face
      MYSQL_USER: dung
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d --user 1000
      - ./db/data:/var/lib/mysql --user 1000
      - ./db/initdb.d:/docker-entrypoint-initdb.d --user 1000
    ports:
      - "3306:3306"