kakao:
  # TODO:change prod server url
  redirect-uri: 'http://localhost:3000/auth/kakao/callback'
  info:
    url: 'https://kapi.kakao.com/v2/user/me'A
  authorize:
    url: 'https://kauth.kakao.com/oauth/authorize'
  token:
    url: 'https://kauth.kakao.com/oauth/token'

jwt:
  access-token:
    expires: '3h'
  refresh-token:
    expires: '12d'
