database:
  host: 'prod-rds'
  port: 3306
  username: 'dung'
  schema: 'face'
  password: '1234'

kakao:
  client-id: '206b93e6e25154a1d06f48c255a8f8b8'
  client-secret: '6rtrT898WeNXZEgF7Mj5z3Ipb6NOoctl'
  redirect-uri: 'http://localhost:3000/auth/kakao/callback'
  authorize:
    url: 'https://kauth.kakao.com/oauth/authorize'
  token:
    url: 'https://kauth.kakao.com/oauth/token'
