kakao:
  redirect-uri: 'http://localhost:3000/auth/kakao/callback'
  info:
    url: 'https://kapi.kakao.com/v2/user/me'
  authorize:
    url: 'https://kauth.kakao.com/oauth/authorize'
  token:
    url: 'https://kauth.kakao.com/oauth/token'

jwt:
  access-token:
    expires: '20s'
  refresh-token:
    expires: '5m'
