kakao:
  info:
    url: 'https://kapi.kakao.com/v2/user/me'
  authorize:
    url: 'https://kauth.kakao.com/oauth/authorize'
  token:
    url: 'https://kauth.kakao.com/oauth/token'

jwt:
  access-token:
    expires: '3h'
  refresh-token:
    expires: '12d'
